version: '3.4'

services:
  nginx:
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ~/.aspnet/https:/etc/ssl/certs:ro
  webapi:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Authentication__AuthorityUrl=https://chatauth.local
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx 
   ports:
     - "8082:443"
     - "8083:80"
   volumes:
     - ~/.aspnet/https:/https:ro
  user-grpc:
    environment:
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8088;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "8088:8088"
      - "8089:443"
  identity-server:
    environment:
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:1000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx 
    ports:
      - "8084:443"
      - "8085:1000"
    volumes:
      - ~/.aspnet/https:/https:ro
  search:
    environment:
      - ASPNETCORE_HTTPS_PORT=443
      - Authentication__AuthorityUrl=https://chatauth.local
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:8087
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    ports:
      - "8086:443"
      - "8087:8087"
    volumes:
      - ~/.aspnet/https:/https:ro
  webclient:
    environment:
      - REACT_APP_AUDIENCE=https://chatauth.local
      - REACT_APP_ISSUER=https://chatauth.local
      - REACT_APP_AUTH_URL=https://chatauth.local
      - REACT_APP_AUTHORITY=https://chatauth.local
    ports:
      - "3000:3000"
  db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  postgres:
    environment:
      POSTGRES_PASSWORD: Pass129598  