version: '3.4'

services:
  nginx:
    container_name: "nginx"
    image: nginx
    build:
      context: "../nginx/"
  user-grpc:
    image: user-grpc
    build:
      context: ../
      dockerfile: services/user-grpc/Dockerfile
    depends_on:
      - db                                                                                
  identity-server:
    container_name: "identity-server"
    image: identity-server
    build:
      context: ../services/
      dockerfile: identity-server/Dockerfile
    depends_on:
      - db
  search:
    container_name: "search"
    image: search
    build:
      context: ../
      dockerfile: services/search/src/Dockerfile
    depends_on:
      - identity-server
  webapi:
    container_name: "webapi"
    image: webapi
    build:
      context: ../services/messages/
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - postgres
  webclient:
    container_name: "webclient"
    image: webclient
    build:
      context: ../
      dockerfile: aspnet-client/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
  postgres:
    container_name: postgres
    image: postgres
