version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
  webapi:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   ports:
     - "8080:80"
  webclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
    ports:
      - "8082:3000"
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1000
    ports:
      - "1000:1000"
  db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"