version: '3.4'

services:
  nginx:
    ports:
      - "443:443"
  webapi:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   ports:
     - "8080:443"
  webclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:443"
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1000:443"
  db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"