version: '3.4'

services:
  nginx:
    container_name: "nginx"
    image: nginx
    build:
      context: "../nginx/"
  webapi:
    container_name: "webapi"
    image: webapi
    build:
      context: ../api/
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - db
  webclient:
    container_name: "webclient"
    image: webclient
    build:
      context: ../
      dockerfile: web-client/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
