version: '3.4'

services:
  nginx:
    container_name: "nginx"
    image: nginx
    build:
      context: "../nginx/"
  identity-server:
    container_name: "identity-server"
    image: identity-server
    build:
      context: ../
      dockerfile: identity-server/Dockerfile
  webapi:
    container_name: "webapi"
    image: webapi
    build:
      context: ../services/messages/
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - db
  webclient:
    container_name: "webclient"
    image: webclient
    build:
      context: ../web-client/
      dockerfile: Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
