version: '3.4'

services:
  nginx:
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ~/.certs:/etc/ssl/certs:ro
  webapi:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx 
   ports:
     - "8080:443"
     - "8081:80"
   volumes:
     - ~/.certs:/https:ro
  identity-server:
    environment:
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:1000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/auth.pfx 
    ports:
      - "8084:443"
      - "8085:1000"
    volumes:
      - ~/.certs:/https:ro
  webclient:
    build:
     args:
       ENV: docker
    ports:
      - "8082:443"
      - "8083:3000"
  db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  postgres:
    environment:
      POSTGRES_PASSWORD: Pass129598  