version: '3.4'

services:
  identity-server:
    container_name: "identity-server"
    image: identity-server
    build:
      context: ../
      dockerfile: identity-server/Dockerfile
  webapi:
    container_name: "webapi"
    image: webapi
    build:
      context: ../api/
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - db
  webclient:
    container_name: "webclient"
    image: webclient
    build:
      context: ../
      dockerfile: web-client/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
